<div id="modules" class="section-block">

    <div class="callout-block callout-success">
        <div class="icon-holder">
            <i class="fa fa-thumbs-up"></i>
        </div><!--//icon-holder-->
        <div class="content">
            <h4 class="callout-title">Useful Tip:</h4>
            <p>
                Be sure to configure all options before start to create your structure
            </p>
        </div><!--//content-->
    </div>
    <div class="code-block">

        <h6>Modules</h6>

        <p>
            CrowPHP breaks down the application into modules for better management, these correspond to independent functionalities that will be handled by the corresponding module.
        </p>

        <h6>Note:</h6>
        <p>
            There is a modules directory that was generated by CrowPHP. You can find as <strong>'Apps'</strong> into root path. You can change the name of this directory if you want, but you need specified this action into <a href="#configuration" class="scrollto">configuration.json</a>
        </p>

        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h6>Module components</h6>
                <ul class="list">
                    <li> <a href="components">Controllers</a> </li>
                    <li> <a href="components">Modules</a> </li>
                    <li> <a href="components">Views</a> </li>
                    <li>js</li>
                    <li>css</li>
                </ul>
            </div>
        </div>

    </div><!--//code-block-->
</div><!--//section-block-->